### ISSUE TITLE
Get the MyoBridge Library to work on stm32duino IDE 

### ISSUE THREAD

**Issue by NBProjects** [vroland/MyoBridge#9]
Hello vroland,

For a university project, I'm trying to get your MyoBridge Library up and running on an STM32 Nucleo F303RE Board by using the stm32duino project (https://github.com/stm32duino/BoardManagerFiles).
First, I programmed an Arduino UNO with the MyoBridge Library and it works fine so far. Then I installed the stm32duino package to the Arduino IDE, tried some basic programs and it also works fine.
But when I want to compile the MyoBridge (basic) projects with the stm32duino board manager, then I get several compiling errors because of missing libraries like "SoftwareSerial.h", "util/delay_basic.h" or "avr/interrupt.h".
I included these libraries manually but there comes up a new error message every time when I try to compile. Can you help me and us by get this running please?

MfG
Noah Boroske

**Comment by vroland** [comment]
Hey NBProjects,
As fpistm already mentioned in the BoardManager issue, you probably have to exchange some AVR-specific libs for stm32-based ones. The SoftwareSerial library, for example, is only used because most AVR-based Arduinos do not have a second UART which would be needed for bridge operation. You can use any hardware serial port instead. 
I don't know about the rest, since I can't test anything myself. But I would imagine you can find replacements for the other libraries as well.
I hope this helps, closing this for now.
Greetings,
Valentin

**Comment by NBProjects** [comment]
Many thanks for your answer! I will try to replace the SoftwareSerial library, for example with the HardwareSerial library. Hopefully this let compile the MyoBridge sketch.

Regards
Noah

**Comment by NBProjects** [comment]
Hello,

After a little break with the project, we're now working on it again and by the replacing of the SoftwareSerial with a (Hardware) Serial, in this case Serial1, we're getting a new failure message as shown in the attached picture. Do you have an idea?

Regards
Noah

![failure 1](https://user-images.githubusercontent.com/37435896/40116622-7afdc75e-5914-11e8-9324-1cae6fb31cd4.JPG)

**Comment by vroland** [comment]
Looks like there is a name collision with some DEFINEs. You could try to fork MyoBridge and rename every occurrence of SUCCESS to something else...

**Comment by NBProjects** [comment]
Thank you for your answer!
